export const LAYOUT = {
  SIDE_NAVBAR_WIDTH: "4rem",
  NAVBAR_ITEM_CONTENT_WIDTH: "20rem",
  TIMELINE: {
    TIMELINE_CONTAINER_HEIGHT: "15rem",
    TRACK_LAYER_HEIGHT: "2rem",
    TRACK_LAYER_HEIGHT_IN_PX: 2 * 16,
    UTILS_LAYER_HEIGHT: "1.8rem",
    LAYER_NAME_STACK_WIDTH: "8rem",
  },
  PROJECT_HEADER_HEIGHT: "3.5rem",
} as const;
